version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      dotnet: 2.2
    commands:
      - yarn --version
      - yarn global add serverless
      - serverless -v 
  build:
    commands:
      - rm -rf ./bin ./vendor Gopkg.lock
      - dep ensure -v
      - env GOOS=linux go build -ldflags="-s -w" -o bin/world world/main.go
      - sls deploy --verbose --stage $target
