version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      golang: 1.13
    commands:
      - yarn --version
      - yarn global add serverless
      - serverless -v 
      - type dep && dep version
  build:
    commands:
      - rm -rf ./bin ./vendor Gopkg.lock
      - dep ensure -v
      - env GOOS=linux go build -ldflags="-s -w" -o bin/batch/delete batch/main.go
      - sls deploy --verbose --stage $target
